/**
 * THIS FILE IS AUTO GENERATED BY THE IGNITER CLI TOOL
 */

import { injectable }         from "inversify";
import { IRestApiController } from "@api/api-controller";
import { Router }             from "express";

@injectable()
export class _CLASS_NAME_ implements IRestApiController {
	baseRoute = "wall";
	public debugMode: boolean;

	public initRoutes(routes: Router): void {
	}
}
